version: "3"
services:
  db:
    image: supabase/postgres:14.1.0
    container_name: mirror-test-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
